apiVersion: v1
kind: PersistentVolume
metadata:
  name: guacamole-rcd
  namespace: system-uat
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy:
    Retain
  nfs:
    path: /tmp/data/guacamole/video
    server: 10.0.15.1
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guacamole-rcd
  namespace: system-uat
spec:
  accessModes:
  - ReadWriteOnce
  resources:
     requests:
       storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: guacamole
  namespace: system-uat
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30080
  selector:
    app: guacamole
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole
  namespace: system-uat
  labels:
   app: guacamole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guacamole	
  template:
    metadata:
      labels:
        app: guacamole
    spec:
      containers:
      - name: guacamole
        image: docker.registry.local:5000/guacamole:v1.${BUILD_NUMBER}
        env:
        - name: MYSQL_HOSTNAME
          value: "mysql.database"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          value: "guacamole"
        - name: MYSQL_PASSWORD
          value: "21121986"
        - name: MYSQL_DATABASE
          value: "guacamole"
        - name: GUACD_HOSTNAME
          value: "guacamole-guacd"
        - name: GUACD_PORT 
          value: "4822"
        ports:
        - containerPort: 8080
          name: guacamole
        volumeMounts:
        - name: guacamole-rcd
          mountPath: /usr/local/tomcat/webapps/player/video
      volumes:
      - name: guacamole-rcd
        persistentVolumeClaim:
          claimName: guacamole-rcd
