apiVersion: v1
kind: Service
metadata:
  name: guacamole
  namespace: system-uat
spec:
  type: NodePort
  ports:
  - targetPort:8080
    port:8080
    nodePort:38080
  selector:
    app: guacamole
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: guacamole
  namespace: system-uat
spec:
  selector:
    matchLabels:
      app: guacamole
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: guacamole
    spec:
      containers:
      - image: guacamole/guacamole:latest
        name: guacamole
        env:
        - name: MYSQL_HOST
          value: "mysql.database"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          value: "guacamole"
        - name: MYSQL_PASSWORD
          value: "21121986
        - name: MYSQL_DATABASE
          value: "guacamole"
        ports:
        - containerPort: 8080
          name: guacamole
