apiVersion: v1
kind: Service
metadata:
  name: guacamole-guacd
  namespace: system-uat
spec:
  ports:
  - port: 4822
  selector:
    app:  guacamole-guacd
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole-guacd
  namespace: system-uat
spec:
  selector:
    matchLabels:
      app: guacamole-guacd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: guacamole-guacd
    spec:
      containers:
      - image: guacamole/guacd:latest
        name: guacamole-guacd
        ports:
        - containerPort: 4822
          name: guacamole-guacd
---
apiVersion: v1
kind: Service
metadata:
  name: guacamole
  namespace: system-uat
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30080
  selector:
    app: guacamole
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole
  namespace: system-uat
  labels:
   app: guacamole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guacamole	
  template:
    metadata:
      labels:
        app: guacamole
    spec:
      containers:
      - name: guacamole
        image: guacamole/guacamole:latest
        env:
        - name: MYSQL_HOST
          value: "mysql.database"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          value: "guacamole"
        - name: MYSQL_PASSWORD
          value: "21121986"
        - name: MYSQL_DATABASE
          value: "guacamole"
        - name: GUACD_HOSTNAME
          value: "guacamole-guacd"
        - name: GUACD_PORT 
          value: "4822"
        ports:
        - containerPort: 8080
          name: guacamole

